apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonwebapplication
  labels:
    app: pythonwebapplication
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythonwebapplication
  template:
    metadata:
      labels:
        app: pythonwebapplication
    spec:
      containers:
      - name: pythonwebapplicationcontainer
        image: svankad/azurepython:45
        ports:
        - containerPort: 8000
